name: Update Topics

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-topics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Detect Python libraries dynamically
        id: detect
        run: |
          TOPICS=""

          # Scanner toutes les librairies du requirements.txt
          if [ -f requirements.txt ]; then
            while IFS= read -r line; do
              # Extraire le nom de la librairie avant ==
              LIB=$(echo "$line" | cut -d '=' -f 1)
              # Ignorer les lignes vides ou commentaires
              if [ -n "$LIB" ] && [[ ! "$LIB" =~ ^# ]]; then
                # Remplacer les underscores par des tirets et capitaliser première lettre
                LIB_FORMATTED=$(echo "$LIB" | sed 's/_/-/g' | awk '{print toupper(substr($0,1,1)) substr($0,2)}')
                TOPICS="$TOPICS,$LIB_FORMATTED"
              fi
            done < requirements.txt
          fi

          # Nettoyer la variable
          TOPICS=$(echo $TOPICS | sed 's/^,//; s/,,/,/g')
          echo "TOPICS=$TOPICS" >> $GITHUB_ENV

      - name: Set repository topics
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_GITHUB }}
          script: |
            const topics = process.env.TOPICS.split(',').map(t => t.trim());
            await github.rest.repos.replaceAllTopics({
              owner: context.repo.owner,
              repo: context.repo.repo,
              names: topics
            });
